version: "3"
services:
  crime-portal-gateway:
    build:
      context: .
    network_mode: "host"
    container_name: crime-portal-gateway
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev,logstash,secure
      - KEYSTORE_PASSWORD=changeit

  localstack:
    image: localstack/localstack:latest
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566-4597:4566-4597"
      - "8999:8080"
      - "9080:9080"
    environment:
      - SERVICES=s3,sqs,sns
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/src/test/resources/localstack/setup-s3.sh:/etc/localstack/init/ready.d/init-aws.sh"

networks:
  hmpps:
