spring:
  logging:
    level:
      org.springframework.web: TRACE
      org.springframework.ws: TRACE
      org.springframework.ws.server.MessageTracing.received: INFO
      org.springframework.ws.server.MessageTracing.sent: INFO
      uk.gov.justice.digital.hmpps.crimeportalgateway.application: TRACE
  mvc:
    log-request-details: true

soap:
  xsd-file-path: src/main/resources/xsd/cp/external/ExternalDocumentRequest.xsd

# Localstack settings
aws:
  sqs-endpoint-url: "http://localhost:4566"
  sns:
    court-case-events-topic: "arn:aws:sns:eu-west-2:000000000000:court-case-events-topic"
  region-name: eu-west-2
  access_key: foobar
  secret_access_key: foobar
  s3:
    access_key: foobar
    secret_access_key: foobar
    access_key_id: foobar
    bucket_name: cpg-bucket
