version: 2.1

parameters:
  alerts-slack-channel:
    type: string
    default: probation_in_court_alerts_dev
  releases-slack-channel:
    type: string
    default: probation_in_court_alerts_prod

orbs:
  hmpps: ministryofjustice/hmpps@10

jobs:
  validate:
    executor:
      name: hmpps/localstack
      jdk_tag: "21.0"
      localstack_tag: "3"
      services: "sqs,sns,s3"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate:
          context: [hmpps-common-vars]
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          context: [hmpps-common-vars]
          name: build_docker
          filters:
            branches:
              only:
                - main
                - /.*deployable_branch.*/
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          helm_additional_args: --values ./crime-portal-gateway/values-live.yaml
          context:
            - hmpps-common-vars
          filters:
            branches:
              only:
                - main
                - /.*deployable_branch.*/
          requires:
            - validate
            - build_docker
            - helm_lint
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          jira_env_type: "staging"
          helm_additional_args: --values ./crime-portal-gateway/values-live.yaml
          context:
            - hmpps-common-vars
            - court-probation-live-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          jira_env_type: "production"
          helm_additional_args: --values ./crime-portal-gateway/values-live.yaml
          context:
            - hmpps-common-vars
            - court-probation-live-prod
          slack_notification: true
          slack_channel_name: << pipeline.parameters.releases-slack-channel >>
          requires:
            - request-prod-approval

  scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
            - veracode-credentials
