version: 2.1

orbs:
  owasp: entur/owasp@0.0.10
  hmpps: ministryofjustice/hmpps@2.1.0
  slack: circleci/slack@4.1.1
  jira: circleci/jira@1.2.2

jobs:
  validate:
    executor: hmpps/java
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - slack/notify:
          event: fail
          custom: |
            {
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "Failed: $CIRCLE_USERNAME's build of \n<$CIRCLE_BUILD_URL|$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME>\n(<https://app.circleci.com/pipelines/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME?branch=$CIRCLE_BRANCH|$CIRCLE_BRANCH>) \n- <$CIRCLE_BUILD_URL|$CIRCLE_JOB> failed"
                        }
                    }
                ]
            }

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
          post-steps:
              - jira/notify:
                job_type: build
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
          post-steps:
            - jira/notify:
              job_type: build
      - hmpps/deploy_env:
          name: deploy_dev
          retrieve_secrets: none
          env: "dev"
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - build_docker
            - helm_lint
#          post-steps:
#            - jira/notify:
#              environment: dev
#              environment_type: development
#              job_type: deployment
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          retrieve_secrets: none
          env: "preprod"
          context: court-probation-preprod
          requires:
            - request-preprod-approval
#          post-steps:
#            - jira/notify:
#              environment: preprod
#              environment_type: testing
#              job_type: deployment
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          retrieve_secrets: none
          env: "prod"
          slack_notification: true
          slack_channel_name: probation_in_court_dev
          context: court-probation-prod
          requires:
            - request-prod-approval
#          post-steps:
#            - jira/notify:
#              environment: prod
#              environment_type: production
#              job_type: deployment

  scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - owasp/gradle_owasp_dependency_check:
          executor: hmpps/java
