version: 2.1

orbs:
  owasp: entur/owasp@0.0.10
  hmpps: ministryofjustice/hmpps@10
  slack: circleci/slack@4.1.1

jobs:
  validate:
    executor:
      name: hmpps/localstack
      jdk_tag: "21.0"
      localstack_tag: "3"
      services: "sqs,sns,s3"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - slack/notify:
          event: fail
          custom: |
            {
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "Failed: $CIRCLE_USERNAME's build of \n<$CIRCLE_BUILD_URL|$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME>\n(<https://app.circleci.com/pipelines/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME?branch=$CIRCLE_BRANCH|$CIRCLE_BRANCH>) \n- <$CIRCLE_BUILD_URL|$CIRCLE_JOB> failed"
                        }
                    }
                ]
            }

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate:
          context: [hmpps-common-vars]
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          context: [hmpps-common-vars]
          name: build_docker
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          filters:
            branches:
              only:
                - main
                - /.*deployable_branch.*/
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          helm_additional_args: --values ./crime-portal-gateway/values-live.yaml
          context:
            - hmpps-common-vars
          filters:
            branches:
              only:
                - main
                - /.*deployable_branch.*/
          requires:
            - validate
            - build_docker
            - helm_lint
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          jira_env_type: "staging"
          helm_additional_args: --values ./crime-portal-gateway/values-live.yaml
          context:
            - hmpps-common-vars
            - court-probation-live-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          jira_env_type: "production"
          helm_additional_args: --values ./crime-portal-gateway/values-live.yaml
          context:
            - hmpps-common-vars
            - court-probation-live-prod
          slack_notification: true
          slack_channel_name: probation_in_court_dev
          requires:
            - request-prod-approval

  scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
        slack_channel: probation_in_court_alerts_prod
        context:
          - hmpps-common-vars
        jdk_tag: "21.0"
        cache_key: "v3_0"
      - hmpps/trivy_latest_scan:
          slack_channel: probation_in_court_alerts_prod
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: probation_in_court_alerts_prod
          context:
            - veracode-credentials
            - hmpps-common-vars
