# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

minReplicaCount: 1
maxReplicaCount: 2

image:
  repository: quay.io/hmpps/crime-portal-gateway
  tag: latest
  port: 8081

ingress:
  enabled: true
  enable_whitelist: true
  hosts:
    - host: crime-portal-gateway-dev.apps.live-1.cloud-platform.service.justice.gov.uk
  path: /mirrorgateway/service/cpmgwextdocapi(/|$)(.*)
  rewrite_target: /crime-portal-gateway/ws/$2

env:
  JAVA_OPTS: "-Xmx512m"
  SPRING_PROFILES_ACTIVE: "dev,logstash"
  INCLUDED_COURT_CODES: "B01KR,B14AV,B03AX,B42AZ,B44BA,B01BE,B10BF,B16BG,B01BH,B20BL,B04BP,B04BQ,B06BV,B32BX,B13CC,B16CJ,B47CL,B01CN,B04CO,B21DA,B46DB,B62DC,B03DE,B42CM,B07DM,B30PG,B01DU,B42CO,B20EB,B07ED,B01EF,B11EI,B30PI,B14ET,B20EY,B01FA,B46FO,B10FR,B16GB,B12GH,B01GQ,B22GR,B01GU,B16HE,B37HI,B22HM,B13HD,B04HQ,B01LY,B23HS,B13HT,B33HU,B32HX,B05PK,B33II,B40IM,B46IR,B06IS,B31IT,B46IU,B46DH,B10BD,B10JL,B11JP,B30PG,B21JI,B10JQ,B34JS,B31JV,B23PP,B11KF,B04KO,B22KS,B01LA,B12LK,B05BW,B46LN,B42MB,B14LO,B12LT,B10LX,B22OS,B06MK,B01MN,B10MR,B62MV,B54MW,B06AN,B17JA,B22MZ,B01ND,B01NM,B20NQ,B07FQ,B23HS,B34NX,B03OT,B01IX,B06OJ,B01CE,B01OK,B05BK,B20OQ,B22OS,B47OV,B12PA"

whitelist:
  office: "217.33.148.210/32"
  health-kick: "35.177.252.195/32"
  mojvpn: "81.134.202.29/32"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"
  bsi-1: "54.37.241.156/30"
  bsi-2: "167.71.136.237/32"
