generic-service:
  autoscaling:
    minReplicas: 2
    maxReplicas: 4

  ingress:
    hosts:
      - preprod.crime-portal-mirror-gateway.service.justice.gov.uk
    tlsSecretName: crime-portal-gateway-cert

  env:
    SPRING_PROFILES_ACTIVE: "preprod,secure,logstash"

  allowlist:
    cgi-test-env: "51.140.207.121/32"
    cgi-nle-env: "40.81.152.12/32"
    cgi-new-test-env-1: "195.206.176.96/27"
    cgi-new-test-env-2: "195.206.178.96/27"

  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 500Mi

generic-prometheus-alerts:
  alertSeverity: probation_in_court_alerts_preprod