# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

minReplicaCount: 2
maxReplicaCount: 4

image:
  repository: quay.io/hmpps/crime-portal-gateway
  tag: latest
  port: 8081

ingress:
  enabled: true
  enable_whitelist: true
  hosts:
    - host: preprod.crime-portal-mirror-gateway.service.justice.gov.uk
      cert_secret: crime-portal-gateway-cert
  path: /mirrorgateway/service/cpmgwextdocapi(/|$)(.*)
  rewrite_target: /crime-portal-gateway/ws/$2

env:
  JAVA_OPTS: "-Xmx512m"
  SPRING_PROFILES_ACTIVE: "preprod,secure,logstash"
  INCLUDED_COURT_CODES: "B01BH,B01CE,B01CN,B01DU,B01EF,B01GU,B01IX,B01ND,B03DE,B03OT,B10BD,B10JJ,B10JQ,B13HT,B14AV,B14ET,B14LO,B16BG,B16GB,B16HE,B17JA,B20BL,B20EB,B20EY,B20NQ,B20OQ,B21DA,B21JI,B22GR,B22HM,B22KS,B22MZ,B22OS,B23HS,B30PG,B31IT,B31JV,B32HX,B32UD,B33HU,B33II,B37HI,B40IM,B44BA,B46IR,B46FO,B46LN,B47CL,B47OV,B54MW,B62DC,B62MV"

whitelist:
  office: "217.33.148.210/32"
  health-kick: "35.177.252.195/32"
  mojvpn: "81.134.202.29/32"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"

resources:
  cpu:
    limit: 1000m
    request: 100m
  memory:
    limit: 1000Mi
    request: 500Mi
